aiidateam/kiwipy

.travis.yml, examples/rmq_rpc_client.py
Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.
__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
=> Travis CI: Add Python 3.7 and flake8 to the testing

.pre-commit-config.yaml, kiwipy/rmq/communicator.py, kiwipy/rmq/messages.py, kiwipy/rmq/tasks.py
The `testing_mode` argument was not being propagated correctly to
all the entities declaring exchanges.
=> Cleanup exchanges and queues in testing mode

kiwipy/rmq/tasks.py
If the call of a task subscriber excepts in `on_task` and
`no_reply=True`, the caller will never be made aware of this unless it
is explicitly logged as an exception. Since the caller specified to not
want a reply, the exception cannot be communicated through the response.
=> Log exception if call of task subscriber excepts for `no_reply=True`

kiwipy/rmq/messages.py, setup.py
Fixes #20 
Currently blocked because the required changes in `topika` have not yet been released
This was deprecated in `pika==1.0.0` and in `topika` by extension
=> Remove the `immediate` keyword from `BasePublisherWithReplyQueue.publish`

.travis.yml, setup.py
Fixes #25 
The only problem is that python 3.7 still requires xenial on Travis
which doesn't come with `rabbitmq` as a service, so we have to install
manually through `sudo apt`.
=> Enable testing for python 3.7 on Travis

kiwipy/rmq/tasks.py
Fixes #29 
Even if the exchange and queues are marked as durable, publishing a
message with the default `delivery_mode=1`, which is non-persistent,
will cause the messages to be lost on a broker restart. Since task
messages have to be persisted, we mark them as such.
=> Mark task messages to be persistent by setting `delivery_mode=2`

README.rst
Some links were still pointing to the old master repo `muhrin` which is
now hosted at `aiidateam`.
=> Fix stale references in the `README.rst`

kiwipy/rmq/defaults.py, setup.py
Fixes #36 
Before `pyyaml==5.1` the `yaml.load` function was vulnerable to
arbitrary code execution, because it loaded the full set of YAML. There
was an alternative `safe_load` but this was not the default and could
only load a sub set of the markup language. The new version of pyyaml
deprecates the old vulnerable code and provides the `FullLoader` that
can load the full set without being vulnerable. The `safe_load` is
syntactic sugar for `load` with `Loader=FullLoader`.
=> Update `pyyaml` to prevent arbitrary code execution

kiwipy/__init__.py, kiwipy/communications.py, kiwipy/exceptions.py, kiwipy/rmq/communicator.py, test/utils.py
These are added on the communicator interface to be able to close and to
have an exception to check against if the communicator is closed.
Test added.
Exceptions have been moved to their own file but references have been
left so that they can still be imported using kiwipy.<exception> not
breaking the API.
=> Added communicator close method and corresponding exception

kiwipy/communications.py, kiwipy/exceptions.py, kiwipy/filters.py, kiwipy/futures.py, kiwipy/local.py, kiwipy/rmq/communicator.py, kiwipy/rmq/defaults.py, kiwipy/rmq/messages.py, kiwipy/rmq/tasks.py, kiwipy/rmq/threadcomms.py, kiwipy/rmq/utils.py, kiwipy/types.py, kiwipy/utils.py, kiwipy/version.py, setup.py, test/rmq/test_rmq_thread_communicator.py, test/rmq/test_tasks.py, test/rmq/utils.py, test/utils.py
This should go on top of #43.
WARNING: This commit introduces API change
Removing RMQ task subscribers was failing beacuse of the way we used to
wrap the function to get it to play nice in the event loop.  Then when
the user would give us the function to unsubscribe we couldn't find it
because, in fact, we held a wrapped function, not the original.
For the sake of simplicity the API has been changed to that of broadcast
and RPC where the user either supplies or is given a unique identifier
which can later be used to remove the subscriber.
This API change will only cause problems for clients that were removing
task subscribers manually (rather than just closing the communicator).
I believe AiiDA just closes the communicator and so should not require
any changes.
Related bug fixed: …
=> Bugfix task subscribers

examples/rmq_broadcast_client.py, examples/rmq_broadcast_server.py, examples/rmq_new_task.py, examples/rmq_rpc_client.py, examples/rmq_rpc_server.py, examples/rmq_worker.py, kiwipy/__init__.py, kiwipy/communicate.py, kiwipy/communications.py, kiwipy/rmq/threadcomms.py, test/utils.py
This uses the URI to determine which backend to use (we only have the
RMQ one anyway) and passes any other arguments on to the corresponding
communicator.  This makes it easier for someone to create a communicator
and also promotes abstraction by seperating the client from the concrete
class that the URI will resolve to.
=> Feature: Added global kiwipy.connect factory

kiwipy/filters.py, test/utils.py
Fixes #34 
and direct match.  This makes sure all three paths through
_ensure_filter are hit.
Added py3.5 compatible regular expression type match
Thought I'd take this opportunity to fix up this issue.
=> Added tests for broadcast filter using regular expr

.travis.yml, docs/source/conf.py, kiwipy/rmq/communicator.py, kiwipy/rmq/tasks.py, kiwipy/rmq/threadcomms.py, setup.py, test/pytest.ini, test/rmq/conftest.py, test/rmq/notebooks/communicator.ipynb, test/rmq/test_coroutine_communicator.py, test/rmq/test_rmq_thread_communicator.py, test/rmq/utils.py
Fixes #52 
Changed connect() so that now it pipes the arguments through to the
class which will spin up the event loop in a separate thread when
start() is called and at that point connect to RMQ.  This way, all the
loop stuff is being done on the separate thread the jupyter is happy.
This necessitated changing the constructor signature for both
RmqCommunicator and RmqThreadCommunicator, however the respective
connect() function signatures remain unchanged.
Added an async_connect() that creates an RmqCommunicator mirroring the
threaded version.  Updated the tests to use this.
Also made it possible to use an environmental variable to change the
RabbitMQ URI because, e.g., gitlab CI doesn't use 'localhost'.
Added jupyter notebook test - this used to fail because of the loop
issues using …
=> Fixed jupyter problem with RmqThreadCommunicator

.travis.yml, setup.py
Fixes #054
~~Note that I intentionally did not update the `python_requires` in the `setup.py` as this wiil prevent it from being installed with py3.5 even though it is *technically* still compatible. We just don't run the CI anymore for this version~~
The original problem of compatibility was fixed in the same PR #50  that introduced it. So there is no need to drop Py3.5 compatibility anymore. Therefore we are just adding explicit Py3.8 compatibility
=> Add explicit compatibility for Python 3.8

kiwipy/rmq/defaults.py
Fixes #60 
This reverts commit 42fb6f893c4bd150757e0cd0cef8c6b195b00007.
Changing the TTL of messages of the task queue was necessary because the
original value of 7 days was not sufficient for the AiiDA use case.
However, when this parameter is changed, one cannot connect to an
existing queue that was configured with the old value. The only way is
to destroy the queue and create a new one. Since this is not feasible
through a Python API, let alone in an automated fashion, this will
render all upgraded AiiDA installations completely broken. The only
solution is to temporarily revert it to the original value.
=> Revert "Increase the default TTL for task messages (#59)"

kiwipy/communications.py, test/test_communications.py
Fixes #61 
The spec of the `Communicator` abstract class stipulates that the
`add_rpc_subscriber` should always return the identifier, even if an
explicit one was passed in. The `CommunicatorHelper` violated this
specification but went unnoticed since it was not tested.
=> Return identifier from `CommunicatorHelper.add_rpc_subscriber`

kiwipy/rmq/utils.py
It was importing the entire `kiwipy` package just to access the
`RemoteException` class. This has been moved within the function scope
where it is used to prevent the cyclic dependency.
=> Fix a cyclic-import in `kiwipy.rmq.utils`

README.rst, docs/source/index.rst
Added box on index page of docs pointing readers to the wiki which explains how they can contribute to kiwiPy.   Also added to README as served by github and pypi (amongst others).
Fixes #65 .
=> Added note to documentation on how to contribute

setup.py
Fixes #47 
Version `0.11.0` of `pytest-asyncio` introduced a change that breaks our
test because the `event_loop` fixture will no longer be run as fast as
possible causing tests that use it to start a different event loop. This
would throw an error saying that the future was attached to a different
event loop. This is fixed in `pytest-asyncio==0.12.0`.
=> Dependencies: update requirement `pytest-asyncio~=0.12`

MIT, setup.py
Added Jason who contributed some docs plus a fix and Sonia who
contributed the logo.
The MIT license has been updated as it was just an old version
copy/pasted from AiiDA and didn't list the correct copyright holders.
=> Added contributors and fixed MIT license

.github/workflows/ci.yml, kiwipy/rmq/messages.py, setup.py
Fixes #085
The change to `BasePublisherWithReplyQueue._on_channel_close`
signature is not related to Python 3.9 but a change in the dependencies
that can call this callback with additional arguments or keyword
arguments which would raise since the signature doesn't alloq it.
=> Dependencies: add support for Python 3.9

.github/workflows/ci.yml, docs/source/index.rst, docs/source/installation.rst, kiwipy/filters.py, kiwipy/rmq/messages.py, setup.py
Fixes #86
Python 3.5 is EOL as of September 13 2020.
=> Drop support for Python 3.5 

.pre-commit-config.yaml, docs/source/examples/kiwipy/emit_log_topic.py, docs/source/examples/kiwipy/new_task.py, docs/source/examples/kiwipy/receive_logs_topic.py, docs/source/examples/kiwipy/rpc_client.py, docs/source/examples/kiwipy/rpc_server.py, docs/source/examples/kiwipy/worker.py, docs/source/examples/pika/emit_log_topic.py, docs/source/examples/pika/new_task.py, docs/source/examples/pika/receive_logs_topic.py, docs/source/examples/pika/rpc_client.py, docs/source/examples/pika/rpc_server.py, docs/source/examples/pika/worker.py, examples/rmq_broadcast_server.py, examples/rmq_rpc_client.py, examples/rmq_worker.py, kiwipy/communicate.py, kiwipy/communications.py, kiwipy/rmq/communicator.py, kiwipy/rmq/messages.py, kiwipy/rmq/tasks.py, kiwipy/rmq/utils.py, test/rmq/test_rmq_thread_communicator.py, test/rmq/test_tasks.py, test/rmq/utils.py
Fixes #87 
Since Python 3.5 is no longer supported, format string interpolations
can now be replaced by f-strings, introduced in Python 3.6, which are
more readable, require less characters and are more efficient.
~~Note that `pylint` issues a warning when using f-strings for log
messages, just as it does for format interpolated strings. The reasoning
is that this is slightly inefficient as the strings are always
interpolated even if the log is discarded, but also by not passing the
formatting parameters as arguments, the available metadata is reduced.
I feel these inefficiencies are premature optimizations as they are
really minimal and don't weigh up against the improved readability and
maintainability of using f-strings.~~
The majority of the conversions were done automatically with …
=> Replace old format string interpolation with f-strings 

kiwipy/rmq/communicator.py, kiwipy/rmq/tasks.py
Add debug logging for sending task/rpc/broadcast to RMQ.
Note aio-pika does have message logging: https://github.com/mosquito/aio-pika/blob/94066fa900d9c08624d936f9b94037640267ac37/aio_pika/exchange.py#L220-L225, but it does not show the message body which is not very useful for debugging aiida-core, e.g.:
```
02/21/2021 06:34:26 AM <1075612> kiwipy.rmq.tasks: [DEBUG] Sending task with routing key 'aiida-49e364abe4394599af772f4bd4dba24a.process.queue' to RMQ queue 'aiida-49e364abe4394599af772f4bd4dba24a.tasks-reply-44cf8e9d-f4ae-4846-a934-8cd0d11d3e4f' (reply=False): {'task': 'continue', 'args': {'pid': 1308, 'nowait': False, 'tag': None}}
02/21/2021 06:34:26 AM <1075612> aio_pika.exchange: [DEBUG] Publishing message with routing key 'aiida-49e364abe4394599af772f4bd4dba24a.process.queue' …
```
=> 👌 IMPROVE: Add RMQ message logging

kiwipy/rmq/threadcomms.py
The `RmqThreadCommunicator` creates a new_event_loop on initialising, and so on close it should also close it.
@muhrin can you think of any reason why this would be an issue?
=> 👌 IMPROVE: close loop on RmqThreadCommunicator.close

kiwipy/rmq/communicator.py, kiwipy/rmq/threadcomms.py, test/rmq/test_rmq_thread_communicator.py
Allow `RmqThreadCommunicator` to be initialised
with a connection_close_callback.
This is an initial step towards addressing https://github.com/aiidateam/aiida-core/issues/4595#issuecomment-788924516.
Note the `aio_pika.RobustConnection` class also has an `add_reconnect_callback` method, but this is not necessary to add if we only want to identify closures (a reconnection is triggered after the `close_callbacks` have been called).
Note also that when these callbacks are called, all exceptions are caught (see https://github.com/mosquito/aio-pika/blob/94066fa900d9c08624d936f9b94037640267ac37/aio_pika/tools.py#L162-L168) which may provide some challenges if the goal is to except the daemon worker 😒 
Oh and one last thing, the callback can be added as "weak=True" (i.e. to a `WeakSet`) which …
=> ✨ NEW: Expose `aio_pika.Connection.add_close_callback`

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/validate_release_tag.py
Various fixes and updates after adopting PEP 621
* Use `flit` to build and upload to PyPI
* Use string for Python version numbers instead of floats
* Install package with `pre-commit` extra for pre-commit step
* Make the tag filter regex more specific to match `vx.y.z`
* Add an explicit check to ensure tag and package version match
=> Devops: update the continuous deployment workflow

src/kiwipy/rmq/threadcomms.py
These were deprecated since `v0.6.0` and were slated to be removed for `v0.7.0`.
=> `RmqThreadCommunicator`: remove deprecated `start` and `stop` methods

pyproject.toml, src/kiwipy/rmq/tasks.py, src/kiwipy/rmq/threadcomms.py, test/rmq/bench/support.py, test/rmq/test_coroutine_communicator.py, test/rmq/test_rmq_thread_communicator.py, test/rmq/test_tasks.py
The release of kiwipy v0.8.0 made some breaking changes to the intended API of RmqThreadCommunicator.  I'm putting back tests that check for the intended API which will be fixed in due time.
=> Reinstanting RmqThreadCommunicator tests

pyproject.toml
This latest version adds official support for Python 3.11.
=> Dependencies: Update requirement `pyyaml~=6.0`
